
# 2
"""Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

"""


def fib(n):
    if n == 1:
        a = [1]
    else:
        a = [1, 1]
    for i in range(2, n):
        a.append(a[i - 1] + a[i - 2])
    return a


def sum_even(array):
    a = []
    counter = 0
    for n in array:
        if n % 2 == 0:
            a.append(n)
        counter += 1
    return sum(a)


x = 2
while fib(x)[x-1] < 4000000:
    x += 1

print(sum_even(fib(x)))