# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
# ten terms would be:
#
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
# Let us list the factors of the first seven triangle numbers:
#
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
#
# What is the value of the first triangle number to have over five hundred divisors?

def trianglenum(n):
    sum = 0
    count = 0
    for i in range(1,n+1):
        for j in range(1,i+1):
            sum += j
        for k in range(1,int(sum**.5)+1):
            if sum % k ==0:
                if (k != sum/k):
                    count +=2
                else:
                    count +=1
            if count >= 500:
                yield sum
                break
        sum = 0
        count = 0

m = trianglenum(100000)
for i in m:
    print(i)
