# 1
"""
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.
"""


"""
f = []

for i in range(1000):
    check_three = i % 3
    check_five = i % 5
    if check_three == 0 or check_five == 0:
        f.append(i)

print(sum(f))
"""


#2
"""Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

"""

def fib(n):
    if n == 1:
        a = [1]
    else:
        a=[1,1]
    for i in range(2,n):
        a.append(a[i-1]+a[i-2])
    return a
    
    
print(fib(1000))

